### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by voxspox** [react-native-community/art#33]
# Bug

    npm install
    npm WARN @react-native-community/art@1.0.1 requires a peer of react-native@^0.59.9 but none is installed. You must install peer dependencies yourself.

## Environment info

package versions:

- "@react-native-community/art": "^1.0.1",
- "react": "16.8.6",
- "react-native": "0.60.5",

## Steps To Reproduce

npm install

Describe what you expected to happen:

no warnings. Why I should install RN 0.59 AND 0.60?

**Comment by Preeternal** [comment]
On my side I got:
`warning " > @react-native-community/art@1.0.1" has incorrect peer dependency "react-native@^0.59.9".
`

**Environment info**
-  "react": "16.9.0",
- "react-native": "0.61.2",

When I opened the simulator, instead of the ART graph - a blank screen.
I'll try to rise the PR to fix it.
